name: Windows build
on: [push]
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2016
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: ./.github/workflows/install.ps1 -arch ${{matrix.arch}}
      - name: Build
        run: ./.github/workflows/build.ps1 -arch ${{matrix.arch}}
      - name: Package
        run: ./.github/workflows/package.ps1 -arch ${{matrix.arch}}
      - name: test
        run: ./.github/workflows/test.ps1 -arch ${{matrix.arch}}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: php_xdiff-dev-7.4-nts-vc15-${{matrix.arch}}
          path: windows_package
